spring:
  application:
    name: microservice-discovery-eureka
# 用户认证配置
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    # 指定profile=peer1时，主机名是peer1
    hostname: peer1
  client:
    service-url:
      # defaultZone: http://localhost:8762/eureka/
      defaultZone: http://user:password@localhost:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    # 指定profile=peer2时，主机名是peer2
    hostname: peer2
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://user:password@localhost:8761/eureka/